/**
 * RunStore — Persistence Contract for Run Lifecycle
 *
 * This module defines the canonical interfaces and Zod schemas for run lifecycle persistence.
 * It is the interface layer for the Store Layer 1.0.0 persistence abstraction.
 *
 * Key Design Decisions:
 * - ID Naming: `runId`, `stepId`, `receiptId` (not generic `id`)
 * - ID Ownership: Caller (orchestration) generates IDs, store is dumb persistence
 * - Timestamps: UTC ISO 8601 strings (YYYY-MM-DDTHH:mm:ss.sssZ) for serialization
 * - NDJSON Coexistence: RunStore does NOT replace audit logs; they remain human-friendly traces
 *
 * @module store/run-store
 */

import { z } from "zod";

// ─────────────────────────────────────────────────────────────────────────────
// Run State Machine
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Run state machine states.
 *
 * @example
 * ```typescript
 * const state: RunState = "running";
 * ```
 */
export const RunStateSchema = z.enum(["pending", "running", "completed", "failed", "aborted"]);
export type RunState = z.infer<typeof RunStateSchema>;

// ─────────────────────────────────────────────────────────────────────────────
// Step Status
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Step outcome status.
 *
 * @example
 * ```typescript
 * const status: StepStatus = "pass";
 * ```
 */
export const StepStatusSchema = z.enum(["pass", "fail", "skipped", "blocked"]);
export type StepStatus = z.infer<typeof StepStatusSchema>;

// ─────────────────────────────────────────────────────────────────────────────
// RunRecord
// ─────────────────────────────────────────────────────────────────────────────

/**
 * A single run record.
 *
 * ID Ownership: `runId` MUST be pre-generated by the caller (orchestration layer).
 * The same runId appears in artifacts, NDJSON logs, and MCP status responses.
 * The store is responsible for persistence, not identity generation.
 *
 * Timestamps: All timestamps MUST be UTC ISO 8601 strings (YYYY-MM-DDTHH:mm:ss.sssZ).
 *
 * @example
 * ```typescript
 * const run: RunRecord = {
 *   runId: "01HXYZ123ABC",
 *   planHash: "sha256:abc123...",
 *   state: "running",
 *   startedAt: "2024-01-15T10:30:00.000Z",
 *   metadata: { prNumber: 42 }
 * };
 * ```
 */
export const RunRecordSchema = z.object({
	/** Caller-provided run identifier. Pre-generated by orchestration. */
	runId: z.string().min(1),

	/** SHA256 hash of the frozen plan.json. */
	planHash: z.string().min(1),

	/** Current state of the run. */
	state: RunStateSchema,

	/** When the run started. UTC ISO 8601. */
	startedAt: z.string().datetime({ message: "startedAt must be UTC ISO 8601 format" }),

	/** When the run completed (if terminal state). UTC ISO 8601. */
	completedAt: z.string().datetime({ message: "completedAt must be UTC ISO 8601 format" }).optional(),

	/** Arbitrary metadata for extensibility. */
	metadata: z.record(z.unknown()).optional(),
});

export type RunRecord = z.infer<typeof RunRecordSchema>;

// ─────────────────────────────────────────────────────────────────────────────
// StepOutcome
// ─────────────────────────────────────────────────────────────────────────────

/**
 * A single step within a run.
 *
 * Timestamps: MUST be UTC ISO 8601 strings.
 *
 * @example
 * ```typescript
 * const step: StepOutcome = {
 *   stepId: "step-001",
 *   runId: "01HXYZ123ABC",
 *   nodeId: "pr-42",
 *   gateName: "lint",
 *   status: "pass",
 *   durationMs: 1234,
 *   timestamp: "2024-01-15T10:30:05.000Z"
 * };
 * ```
 */
export const StepOutcomeSchema = z.object({
	/** Unique step identifier. Caller-generated. */
	stepId: z.string().min(1),

	/** Parent run identifier. */
	runId: z.string().min(1),

	/** Node (PR/item) identifier from plan. */
	nodeId: z.string().min(1),

	/** Gate name (e.g., "lint", "typecheck", "test"). */
	gateName: z.string().min(1),

	/** Outcome status. */
	status: StepStatusSchema,

	/** Execution duration in milliseconds. */
	durationMs: z.number().int().nonnegative(),

	/** Optional log output or path. */
	logs: z.string().optional(),

	/** Optional artifact paths. */
	artifacts: z.array(z.string()).optional(),

	/** When this step was recorded. UTC ISO 8601. */
	timestamp: z.string().datetime({ message: "timestamp must be UTC ISO 8601 format" }),
});

export type StepOutcome = z.infer<typeof StepOutcomeSchema>;

// ─────────────────────────────────────────────────────────────────────────────
// Receipt
// ─────────────────────────────────────────────────────────────────────────────

/**
 * A receipt recording scope/risk changes requiring human approval.
 *
 * Timestamps: MUST be UTC ISO 8601 strings.
 *
 * @example
 * ```typescript
 * const receipt: Receipt = {
 *   receiptId: "receipt-001",
 *   runId: "01HXYZ123ABC",
 *   reason: "Scope expanded beyond initial plan",
 *   approver: "alice@example.com",
 *   timestamp: "2024-01-15T10:31:00.000Z"
 * };
 * ```
 */
export const ReceiptSchema = z.object({
	/** Unique receipt identifier. Caller-generated. */
	receiptId: z.string().min(1),

	/** Parent run identifier. */
	runId: z.string().min(1),

	/** Reason for the scope/risk escalation. */
	reason: z.string().min(1),

	/** Human who approved (if applicable). */
	approver: z.string().optional(),

	/** When this receipt was created. UTC ISO 8601. */
	timestamp: z.string().datetime({ message: "timestamp must be UTC ISO 8601 format" }),
});

export type Receipt = z.infer<typeof ReceiptSchema>;

// ─────────────────────────────────────────────────────────────────────────────
// RunStore Interface
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Options for listing runs.
 */
export interface ListRunsOptions {
	/** Maximum number of runs to return. */
	limit?: number;
	/** Number of runs to skip (for pagination). */
	offset?: number;
	/** Filter by run state. */
	state?: RunState;
}

/**
 * RunStore — persistence contract for run lifecycle.
 *
 * Default: InMemoryRunStore (CLI).
 * Future: SqliteRunStore, PostgresRunStore.
 *
 * Note: RunStore provides structured access to runs/steps/receipts.
 * It does NOT replace NDJSON audit logs — those remain the human-friendly trace.
 *
 * @example
 * ```typescript
 * // Create a run
 * await store.createRun({
 *   runId: "run-001",
 *   planHash: "sha256:abc123",
 *   state: "pending",
 *   startedAt: new Date().toISOString()
 * });
 *
 * // Update run state
 * await store.updateRun("run-001", { state: "running" });
 *
 * // Append step outcomes
 * await store.appendStep({
 *   stepId: "step-001",
 *   runId: "run-001",
 *   nodeId: "pr-42",
 *   gateName: "lint",
 *   status: "pass",
 *   durationMs: 1234,
 *   timestamp: new Date().toISOString()
 * });
 *
 * // Get run details
 * const run = await store.getRun("run-001");
 *
 * // Clean up
 * await store.close();
 * ```
 */
export interface RunStore {
	// ─────────────────────────────────────────────────────────────────────────
	// Run CRUD
	// ─────────────────────────────────────────────────────────────────────────

	/**
	 * Create a new run record.
	 *
	 * @param run - The run record to create (runId must be pre-generated by caller)
	 * @throws If run with same runId already exists
	 */
	createRun(run: RunRecord): Promise<void>;

	/**
	 * Update an existing run record.
	 *
	 * @param runId - The run identifier to update
	 * @param updates - Partial updates to apply (runId cannot be changed)
	 * @throws If run with given runId does not exist
	 */
	updateRun(runId: string, updates: Partial<Omit<RunRecord, "runId">>): Promise<void>;

	/**
	 * Get a run record by ID.
	 *
	 * @param runId - The run identifier
	 * @returns The run record, or null if not found
	 */
	getRun(runId: string): Promise<RunRecord | null>;

	/**
	 * List run records with optional filtering and pagination.
	 *
	 * @param options - Optional filtering and pagination options
	 * @returns Array of run records matching the criteria
	 */
	listRuns(options?: ListRunsOptions): Promise<RunRecord[]>;

	// ─────────────────────────────────────────────────────────────────────────
	// Step outcomes
	// ─────────────────────────────────────────────────────────────────────────

	/**
	 * Append a step outcome to a run.
	 *
	 * @param step - The step outcome to append
	 */
	appendStep(step: StepOutcome): Promise<void>;

	/**
	 * Get all step outcomes for a run.
	 *
	 * @param runId - The run identifier
	 * @returns Array of step outcomes for the run
	 */
	getStepsForRun(runId: string): Promise<StepOutcome[]>;

	// ─────────────────────────────────────────────────────────────────────────
	// Receipts
	// ─────────────────────────────────────────────────────────────────────────

	/**
	 * Save a receipt for scope/risk escalation.
	 *
	 * @param receipt - The receipt to save
	 */
	saveReceipt(receipt: Receipt): Promise<void>;

	/**
	 * Get all receipts for a run.
	 *
	 * @param runId - The run identifier
	 * @returns Array of receipts for the run
	 */
	getReceiptsForRun(runId: string): Promise<Receipt[]>;

	// ─────────────────────────────────────────────────────────────────────────
	// Utility
	// ─────────────────────────────────────────────────────────────────────────

	/**
	 * Get the count of runs, optionally filtered by state.
	 *
	 * @param state - Optional state filter
	 * @returns Number of runs matching the criteria
	 */
	getRunCount(state?: RunState): Promise<number>;

	/**
	 * Close the store and release any resources.
	 * Should be called when the store is no longer needed.
	 */
	close(): Promise<void>;
}

// ─────────────────────────────────────────────────────────────────────────────
// Validation Utilities
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Validate and parse a RunRecord.
 *
 * @param data - The data to validate
 * @returns The validated RunRecord
 * @throws {z.ZodError} If validation fails
 */
export function parseRunRecord(data: unknown): RunRecord {
	return RunRecordSchema.parse(data);
}

/**
 * Safely parse a RunRecord, returning a result object.
 *
 * @param data - The data to validate
 * @returns Success with data, or failure with error
 */
export function safeParseRunRecord(data: unknown): z.SafeParseReturnType<unknown, RunRecord> {
	return RunRecordSchema.safeParse(data);
}

/**
 * Validate and parse a StepOutcome.
 *
 * @param data - The data to validate
 * @returns The validated StepOutcome
 * @throws {z.ZodError} If validation fails
 */
export function parseStepOutcome(data: unknown): StepOutcome {
	return StepOutcomeSchema.parse(data);
}

/**
 * Safely parse a StepOutcome, returning a result object.
 *
 * @param data - The data to validate
 * @returns Success with data, or failure with error
 */
export function safeParseStepOutcome(data: unknown): z.SafeParseReturnType<unknown, StepOutcome> {
	return StepOutcomeSchema.safeParse(data);
}

/**
 * Validate and parse a Receipt.
 *
 * @param data - The data to validate
 * @returns The validated Receipt
 * @throws {z.ZodError} If validation fails
 */
export function parseReceipt(data: unknown): Receipt {
	return ReceiptSchema.parse(data);
}

/**
 * Safely parse a Receipt, returning a result object.
 *
 * @param data - The data to validate
 * @returns Success with data, or failure with error
 */
export function safeParseReceipt(data: unknown): z.SafeParseReturnType<unknown, Receipt> {
	return ReceiptSchema.safeParse(data);
}
