<Project>
  <PropertyGroup>
    <AnalysisLevel>latest</AnalysisLevel>
    <Deterministic>true</Deterministic>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OS Condition="'$(OS)' == '' and $([MSBuild]::IsOSPlatform('Windows'))">Windows_NT</OS>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
