/**
 * InMemoryRunStore — In-Memory Implementation of RunStore
 *
 * A fast, deterministic test double that doesn't require SQLite setup.
 * Uses Map<string, RunRecord> and nested maps for steps/receipts.
 *
 * @module store/inmemory/run-store
 */

import type {
  RunStore,
  RunRecord,
  StepOutcome,
  Receipt,
  ListRunsOptions,
  RunState,
} from "../run-store.js";

/**
 * Options for pre-populating the InMemoryRunStore.
 */
export interface InMemoryRunStoreOptions {
  /** Pre-populate with run records. */
  runs?: RunRecord[];
  /** Pre-populate with step outcomes. */
  steps?: StepOutcome[];
  /** Pre-populate with receipts. */
  receipts?: Receipt[];
}

/**
 * InMemoryRunStore — In-memory implementation of the RunStore interface.
 *
 * Provides a fast, deterministic test double for unit testing.
 * All operations are synchronous but wrapped in Promise for interface compliance.
 *
 * @example
 * ```typescript
 * const store = new InMemoryRunStore();
 *
 * await store.createRun({
 *   runId: "run-001",
 *   planHash: "sha256:abc123",
 *   state: "pending",
 *   startedAt: new Date().toISOString()
 * });
 *
 * const run = await store.getRun("run-001");
 * console.log(run?.state); // "pending"
 * ```
 */
export class InMemoryRunStore implements RunStore {
  private runs = new Map<string, RunRecord>();
  private steps = new Map<string, StepOutcome[]>(); // keyed by runId
  private receipts = new Map<string, Receipt[]>(); // keyed by runId

  /**
   * Create a new InMemoryRunStore, optionally pre-populated with data.
   *
   * @param options - Optional pre-population options for test setup
   */
  constructor(options?: InMemoryRunStoreOptions) {
    if (options?.runs) {
      for (const run of options.runs) {
        this.runs.set(run.runId, run);
      }
    }

    if (options?.steps) {
      for (const step of options.steps) {
        const existing = this.steps.get(step.runId) ?? [];
        this.steps.set(step.runId, [...existing, step]);
      }
    }

    if (options?.receipts) {
      for (const receipt of options.receipts) {
        const existing = this.receipts.get(receipt.runId) ?? [];
        this.receipts.set(receipt.runId, [...existing, receipt]);
      }
    }
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Run CRUD
  // ─────────────────────────────────────────────────────────────────────────

  /**
   * Create a new run record.
   *
   * @param run - The run record to create (runId must be pre-generated by caller)
   * @throws Error if run with same runId already exists
   */
  async createRun(run: RunRecord): Promise<void> {
    if (this.runs.has(run.runId)) {
      throw new Error(`Run with runId "${run.runId}" already exists`);
    }
    this.runs.set(run.runId, run);
  }

  /**
   * Update an existing run record.
   *
   * @param runId - The run identifier to update
   * @param updates - Partial updates to apply (runId cannot be changed)
   * @throws Error if run with given runId does not exist
   */
  async updateRun(runId: string, updates: Partial<Omit<RunRecord, "runId">>): Promise<void> {
    const existing = this.runs.get(runId);
    if (!existing) {
      throw new Error(`Run with runId "${runId}" not found`);
    }
    this.runs.set(runId, { ...existing, ...updates });
  }

  /**
   * Get a run record by ID.
   *
   * @param runId - The run identifier
   * @returns The run record, or null if not found
   */
  async getRun(runId: string): Promise<RunRecord | null> {
    return this.runs.get(runId) ?? null;
  }

  /**
   * List run records with optional filtering and pagination.
   *
   * @param options - Optional filtering and pagination options
   * @returns Array of run records matching the criteria
   */
  async listRuns(options?: ListRunsOptions): Promise<RunRecord[]> {
    let result = Array.from(this.runs.values());

    // Filter by state if provided
    if (options?.state) {
      result = result.filter((run) => run.state === options.state);
    }

    // Sort by startedAt descending for deterministic ordering
    result.sort((a, b) => {
      const aTime = new Date(a.startedAt).getTime();
      const bTime = new Date(b.startedAt).getTime();
      return bTime - aTime;
    });

    // Apply pagination
    const offset = options?.offset ?? 0;
    const limit = options?.limit;

    if (limit !== undefined) {
      result = result.slice(offset, offset + limit);
    } else if (offset > 0) {
      result = result.slice(offset);
    }

    return result;
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Step outcomes
  // ─────────────────────────────────────────────────────────────────────────

  /**
   * Append a step outcome to a run.
   *
   * @param step - The step outcome to append
   */
  async appendStep(step: StepOutcome): Promise<void> {
    const existing = this.steps.get(step.runId) ?? [];
    this.steps.set(step.runId, [...existing, step]);
  }

  /**
   * Get all step outcomes for a run.
   *
   * @param runId - The run identifier
   * @returns Array of step outcomes for the run
   */
  async getStepsForRun(runId: string): Promise<StepOutcome[]> {
    return this.steps.get(runId) ?? [];
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Receipts
  // ─────────────────────────────────────────────────────────────────────────

  /**
   * Save a receipt for scope/risk escalation.
   *
   * @param receipt - The receipt to save
   */
  async saveReceipt(receipt: Receipt): Promise<void> {
    const existing = this.receipts.get(receipt.runId) ?? [];
    this.receipts.set(receipt.runId, [...existing, receipt]);
  }

  /**
   * Get all receipts for a run.
   *
   * @param runId - The run identifier
   * @returns Array of receipts for the run
   */
  async getReceiptsForRun(runId: string): Promise<Receipt[]> {
    return this.receipts.get(runId) ?? [];
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Utility
  // ─────────────────────────────────────────────────────────────────────────

  /**
   * Get the count of runs, optionally filtered by state.
   *
   * @param state - Optional state filter
   * @returns Number of runs matching the criteria
   */
  async getRunCount(state?: RunState): Promise<number> {
    if (state === undefined) {
      return this.runs.size;
    }
    let count = 0;
    for (const run of this.runs.values()) {
      if (run.state === state) {
        count++;
      }
    }
    return count;
  }

  /**
   * Close the store and release any resources.
   * No-op for in-memory store.
   */
  async close(): Promise<void> {
    // No-op for memory store
  }

  // ─────────────────────────────────────────────────────────────────────────
  // Test Helpers
  // ─────────────────────────────────────────────────────────────────────────

  /**
   * Clear all data from the store.
   * Useful for test cleanup.
   */
  clear(): void {
    this.runs.clear();
    this.steps.clear();
    this.receipts.clear();
  }

  /**
   * Get the current snapshot of all data.
   * Useful for debugging and assertions.
   */
  snapshot(): {
    runs: RunRecord[];
    steps: Map<string, StepOutcome[]>;
    receipts: Map<string, Receipt[]>;
  } {
    return {
      runs: Array.from(this.runs.values()),
      steps: new Map(this.steps),
      receipts: new Map(this.receipts),
    };
  }
}
